import Vue from 'vue';
import { 
    Button,
    NavBar,
    Icon,
    Notify,
    Toast,
    Col, 
    Row,
    Grid, 
    GridItem,
    IndexBar, 
    IndexAnchor,
    Search,
    Cell, 
    CellGroup,
    Skeleton,
    Loading,
    Swipe, 
    SwipeItem,
    DropdownMenu, 
    DropdownItem,
    TreeSelect,
    Switch,
    Tabbar, 
    TabbarItem,
    Card,
    List,
    Tag,
    Rate,
    Divider,
    Popup,
    Tab,
    Tabs,
    GoodsAction, 
    GoodsActionIcon, 
    GoodsActionButton,
    Dialog,
    Sku,
    RadioGroup, 
    Radio,
    Form,
    Field,
    CouponCell,
     CouponList,
     ContactCard
} from 'vant';

Vue.use(ContactCard)
Vue.use(CouponCell)
Vue.use(CouponList)
Vue.use(Toast)
Vue.use(Form)
Vue.use(Field)
Vue.use(RadioGroup)
Vue.use(Radio)
Vue.use(Sku)
Vue.use(Dialog)
Vue.use(GoodsAction)
Vue.use(GoodsActionIcon)
Vue.use(GoodsActionButton)
Vue.use(Tabs)
Vue.use(Tab)
Vue.use(Popup)
Vue.use(Divider)
Vue.use(Rate)
Vue.use(Tag)
Vue.use(List)
Vue.use(Card)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Button)
Vue.use(NavBar)
Vue.use(Icon)
Vue.use(Notify)
Vue.use(Col)
Vue.use(Row)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(IndexBar)
Vue.use(IndexAnchor)
Vue.use(Search)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Skeleton)
Vue.use(Loading)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(TreeSelect)
Vue.use(Switch)